[package]
name = "watchAnime"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = "4.0"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
