[package]
name = "watchAnime"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.0"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
indicatif = "0.16"