use clap::{Arg, Command};

pub fn build_cli() -> Command {
    Command::new("watchAnime")
        .version("1.0")
        .author("Your Name <your.email@example.com>")
        .about("A CLI tool to search and watch anime")
        .arg(Arg::new("query").help("Anime query").required(false))
        .arg(Arg::new("continue").long("continue").help("Continue watching from history"))
        .arg(Arg::new("download").long("download").help("Download the video instead of playing it"))
        .arg(Arg::new("delete").long("delete").help("Delete history"))
        .arg(Arg::new("syncplay").long("syncplay").help("Use Syncplay to watch with friends"))
        .arg(Arg::new("select-nth").long("select-nth").help("Select nth entry").value_name("N"))
        .arg(Arg::new("quality").long("quality").help("Specify the video quality").value_name("QUALITY"))
        .arg(Arg::new("vlc").short('v').long("vlc").help("Use VLC to play the video"))
        .arg(Arg::new("version").long("version").help("Show the version of the script"))
        .arg(Arg::new("help").long("help").help("Show this help message and exit"))
        .arg(Arg::new("episode").long("episode").help("Specify the number of episodes to watch").value_name("EPISODES"))
        .arg(Arg::new("dub").long("dub").help("Play dubbed version"))
        .arg(Arg::new("rofi").long("rofi").help("Use rofi instead of fzf for the interactive menu"))
        .arg(Arg::new("skip").long("skip").help("Use ani-skip to skip the intro of the episodes"))
        .arg(Arg::new("no-detach").long("no-detach").help("Don't detach the player (useful for in-terminal players)"))
        .arg(Arg::new("exit-after-play").long("exit-after-play").help("Exit the player, and return the player exit code"))
        .arg(Arg::new("skip-title").long("skip-title").help("Use given title as ani-skip query").value_name("TITLE"))
        .arg(Arg::new("next-ep-countdown").long("next-ep-countdown").help("Display a countdown to the next episode"))
        .arg(Arg::new("update").long("update").help("Update the script"))
}
